sudo: required
dist: trusty
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_VERSION=default
  - EMBER_VERSION=release
  - EMBER_VERSION=beta
  - EMBER_VERSION=canary
  - DOCKER_HUB_ACCOUNT=rastopyr
  - MAIN_BRANCHES="master develop"
  - RELEASE_BRANCH="master"

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test
  - ./bin/semverinc.sh
  - ./bin/build.sh

after_install:
  - ./bin/push.sh
